#!/usr/bin/env python3
"""
Current Settings Backup - 2025-07-09
Bu dosya mevcut site ayarlarının backup'ını içerir
"""

# Mevcut ayarları içeren backup data
CURRENT_SETTINGS_BACKUP = {
    "logo2_width": 120,
    "header_show_language": False,
    "social_twitter": "@pebdeq",
    "footer_social_show_section": True,
    "homepage_products_show_rating": True,
    "products_page_show_images": True,
    "logo2_height": 40,
    "header_show_currency": False,
    "social_youtube": None,
    "footer_newsletter_title": "Newsletter",
    "homepage_products_show_quick_view": True,
    "products_page_image_height": 200,
    "header_background_color": "#999999",
    "marquee_enabled": True,
    "social_linkedin": None,
    "footer_newsletter_show_section": True,
    "homepage_products2_show_section": True,
    "products_page_image_width": 300,
    "header_text_color": "#2c3e50",
    "marquee_text": "Welcome to our store! Special offers available now.",
    "meta_title": "PEBDEQ - Craft, Vintage, Innovation",
    "footer_newsletter_description": "Subscribe to get updates about new products and offers.",
    "homepage_products2_title": "Latest Products",
    "products_page_show_favorite": True,
    "header_height": 60,
    "marquee_font_family": "Arial, sans-serif",
    "meta_description": "Discover unique 3D printed items, vintage tools, antique light bulbs, and custom laser engraving services.",
    "footer_newsletter_placeholder": "Enter your email address",
    "homepage_products2_subtitle": "Check out our newest arrivals",
    "products_page_show_buy_now": True,
    "header_padding": 10,
    "marquee_font_size": "12px",
    "meta_keywords": "3D printing, vintage tools, antique bulbs, laser engraving, custom products",
    "footer_newsletter_button_text": "Subscribe",
    "homepage_products2_max_rows": 2,
    "products_page_show_details": True,
    "header_sticky": True,
    "marquee_font_weight": "lighter",
    "currency_symbol": "$",
    "homepage_products_show_section": True,
    "homepage_products2_per_row": 4,
    "products_page_show_price": True,
    "header_shadow": True,
    "marquee_color": "#ffffff",
    "currency_code": "USD",
    "homepage_products_title": "Featured Products",
    "homepage_products2_max_items": 8,
    "products_page_show_original_price": True,
    "header_border_bottom": True,
    "marquee_background_color": "#bca9a9",
    "shipping_cost": 15.0,
    "homepage_products_subtitle": "Discover our most popular items",
    "homepage_products2_show_images": True,
    "products_page_show_stock": True,
    "header_border_color": "#eddd26",
    "marquee_speed": 30,
    "free_shipping_threshold": 200.0,
    "homepage_products_max_rows": 2,
    "homepage_products2_image_height": 200,
    "products_page_show_category": True,
    "header_logo_position": "left",
    "marquee_direction": "left",
    "enable_reviews": True,
    "homepage_products_per_row": 4,
    "homepage_products2_image_width": 300,
    "products_page_default_sort_by": "newest",
    "header_nav_position": "right",
    "marquee_pause_on_hover": True,
    "enable_wishlist": True,
    "homepage_products_max_items": 8,
    "homepage_products2_show_favorite": True,
    "products_page_card_style": "modern",
    "header_nav_spacing": 20,
    "welcome_title": "Craft, Vintage, Innovation",
    "enable_compare": True,
    "homepage_products_show_images": True,
    "homepage_products2_show_buy_now": True,
    "products_page_card_shadow": True,
    "navigation_links": [
        {
            "id": 1,
            "title": "Home",
            "url": "/",
            "enabled": True,
            "order": 1,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 2,
            "title": "Products",
            "url": "/products",
            "enabled": True,
            "order": 2,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 3,
            "title": "About",
            "url": "/about",
            "enabled": True,
            "order": 3,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 4,
            "title": "Blog",
            "url": "/blog",
            "enabled": True,
            "order": 4,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 5,
            "title": "Contact",
            "url": "/contact",
            "enabled": True,
            "order": 5,
            "is_internal": True,
            "show_for": "all",
            "type": "page"
        },
        {
            "id": 6,
            "title": "Login",
            "url": "/login",
            "enabled": True,
            "order": 6,
            "is_internal": True,
            "show_for": "guest",
            "type": "auth"
        },
        {
            "id": 7,
            "title": "Register",
            "url": "/register",
            "enabled": True,
            "order": 7,
            "is_internal": True,
            "show_for": "guest",
            "type": "auth"
        },
        {
            "id": 8,
            "title": "Profile",
            "url": "/profile",
            "enabled": True,
            "order": 8,
            "is_internal": True,
            "show_for": "user",
            "type": "auth"
        },
        {
            "id": 9,
            "title": "Admin",
            "url": "/admin",
            "enabled": True,
            "order": 9,
            "is_internal": True,
            "show_for": "admin",
            "type": "auth"
        },
        {
            "id": 10,
            "title": "Logout",
            "url": "logout",
            "enabled": True,
            "order": 10,
            "is_internal": True,
            "show_for": "user",
            "type": "auth"
        }
    ],
    "welcome_subtitle": "Discover unique products and custom designs",
    "enable_newsletter": True,
    "homepage_products_image_height": 200,
    "homepage_products2_show_details": True,
    "products_page_card_hover_effect": True,
    "nav_link_color": "#ffffff",
    "welcome_background_image": None,
    "maintenance_mode": False,
    "homepage_products_image_width": 300,
    "homepage_products2_show_price": True,
    "products_page_show_badges": True,
    "nav_link_hover_color": "#0f57a3",
    "welcome_background_color": "#b9b9b9",
    "footer_show_section": True,
    "homepage_products_show_favorite": True,
    "homepage_products2_show_original_price": True,
    "products_page_show_rating": True,
    "nav_link_active_color": "#007bff",
    "welcome_text_color": "#ffffff",
    "footer_background_color": "#2c3e50",
    "homepage_products_show_buy_now": True,
    "homepage_products2_show_stock": True,
    "products_page_show_quick_view": True,
    "mobile_nav_hamburger_color": "#2c3e50",
    "welcome_button_text": "Shop Now",
    "footer_text_color": "#ffffff",
    "homepage_products_show_details": True,
    "homepage_products2_show_category": True,
    "products_page_enable_pagination": True,
    "nav_link_font_size": 16,
    "welcome_button_link": "/products",
    "footer_company_name": "pebdeq",
    "homepage_products_show_price": True,
    "homepage_products2_sort_by": "newest",
    "products_page_enable_filters": True,
    "nav_link_font_weight": "500",
    "welcome_button_color": "#00b894",
    "footer_company_description": "Crafted with passion, delivered with precision.",
    "homepage_products_show_original_price": True,
    "homepage_products2_filter_categories": [],
    "products_page_enable_search": True,
    "nav_link_text_transform": "none",
    "homepage_background_color": "#e0e0e0",
    "footer_copyright_text": "© 2024 PEBDEQ. All rights reserved.",
    "homepage_products_show_stock": True,
    "homepage_products2_show_view_all": True,
    "nav_link_underline": False,
    "collections_title": "Our Collections",
    "footer_use_logo": False,
    "homepage_products_show_category": True,
    "homepage_products2_view_all_text": "View All Products",
    "nav_link_hover_effect": "color",
    "collections_show_categories": [],
    "footer_logo": None,
    "homepage_products_sort_by": "price_low",
    "homepage_products2_view_all_link": "/products",
    "site_name": "pebdeq",
    "nav_link_font_family": "'Roboto', sans-serif",
    "collections_categories_per_row": 4,
    "footer_logo_width": 120,
    "homepage_products_filter_categories": [],
    "homepage_products2_card_style": "modern",
    "nav_link_text_shadow": True,
    "collections_max_rows": 1,
    "footer_logo_height": 40,
    "homepage_products_show_view_all": True,
    "homepage_products2_card_shadow": True,
    "site_logo": None,
    "mobile_nav_enabled": True,
    "collections_show_section": True,
    "footer_support_title": "Support",
    "homepage_products_view_all_text": "View All Products",
    "homepage_products2_card_hover_effect": True,
    "use_logo": False,
    "mobile_nav_background_color": "#ffffff",
    "contact_phone": "+12223334455",
    "footer_support_show_section": True,
    "homepage_products_view_all_link": "/products",
    "homepage_products2_show_badges": True,
    "logo_width": 120,
    "mobile_nav_overlay": True,
    "contact_email": "info@pebdeq.com",
    "footer_support_links": [
        {
            "title": "Contact Us",
            "url": "/contact",
            "is_external": False
        },
        {
            "title": "FAQ",
            "url": "/faq",
            "is_external": False
        },
        {
            "title": "Shipping Info",
            "url": "/shipping",
            "is_external": False
        },
        {
            "title": "Returns",
            "url": "/returns",
            "is_external": False
        }
    ],
    "homepage_products_card_style": "modern",
    "homepage_products2_show_rating": True,
    "logo_height": 30,
    "mobile_nav_slide_direction": "left",
    "contact_address": "Virginia",
    "footer_quick_links_title": "Quick Links",
    "homepage_products_card_shadow": True,
    "homepage_products2_show_quick_view": True,
    "site_logo2": None,
    "header_show_search": False,
    "social_instagram": "@pebdeq",
    "footer_quick_links_show_section": True,
    "homepage_products_card_hover_effect": True,
    "products_page_background_color": "#e0e0e0",
    "use_logo2": False,
    "header_show_cart": False,
    "social_facebook": "pebdeq",
    "footer_quick_links": [
        {
            "is_external": False,
            "title": "About Us",
            "url": "/about"
        },
        {
            "is_external": False,
            "title": "Products",
            "url": "/products"
        },
        {
            "is_external": False,
            "title": "Blog",
            "url": "/blog"
        },
        {
            "is_external": False,
            "title": "Privacy Policy",
            "url": "/privacy"
        },
        {
            "title": "Admin",
            "url": "/admin",
            "is_external": False
        }
    ],
    "homepage_products_show_badges": True,
    "products_page_per_row": 4,
    "header_show_account": True,
    "footer_social_title": "Follow Us",
    "products_page_max_items_per_page": 12
}

if __name__ == "__main__":
    print("Current Settings Backup loaded successfully!")
    print(f"Total settings: {len(CURRENT_SETTINGS_BACKUP)}") 